version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_DEBUG=1
      - OLLAMA_URL=http://ollama:11434/api/generate
      - UPLOADS_DIR=/app/uploads
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/data:/app/data
      - ./backend/.env:/app/.env:ro
    depends_on:
      - ollama

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      - ./frontend:/app
    command: sh -lc "npm run dev -- -p 3000 -H 0.0.0.0"

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama

  ollama-init:
    image: ollama/ollama:latest
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434
    volumes:
      - ollama_models:/root/.ollama
    entrypoint: ["/bin/sh", "-lc", "for i in $(seq 1 20); do ollama pull duckdb-nsql && exit 0; echo 'waiting for ollama…'; sleep 5; done; exit 0"]
    restart: "no"

volumes:
  ollama_models:
